chore: fix reelect test
xline-kv/Xline pull request #500
Opened 2023-11-02 02:46 UTC by themanforfree

Please briefly answer these questions:

* what problem are you trying to solve? (or if there's no problem, what's the motivation for this change?)
fix reelect test
* what changes does this pull request make?
modify assert in this test
* are there any non-obvious implications of these changes? (does it break compatibility with previous versions, etc)
no

2023-11-03 04:41 UTC, iGxnon approved these changes

2023-11-06 01:12 UTC, Phoenix500526 requested changes
Please correct the typo in the conflict_checked_mpmc.rs

2023-11-06 02:20 UTC, rogercloud approved these changes

2023-11-06 02:24 UTC, bsbds approved these changes

2023-11-06 04:02 UTC, Phoenix500526 approved these changes

2023-11-06 04:02 UTC, merged